retail_analytics:
  outputs:
    dev:
      account: ***********************************
      database: dbt_retail_catalog
      password: **********************************
      role: TRANSFORM
      schema: dbt_santosh
      threads: 1
      type: snowflake
      user: dbt_user
      warehouse: COMPUTE_WH
    uat:
      account: ***********************************
      database: dbt_retail_catalog
      password: **********************************
      role: TRANSFORM
      schema: dbt_santosh
      threads: 1
      type: snowflake
      user: dbt_user
      warehouse: COMPUTE_WH
    prod:
      account: ***********************************
      database: dbt_retail_catalog
      password: **********************************
      role: TRANSFORM
      schema: dbt_santosh
      threads: 1
      type: snowflake
      user: dbt_user
      warehouse: COMPUTE_WH
  target: dev
